### ISSUE TITLE
Package.json `browserslist` field as source for browsers

### ISSUE THREAD

**Issue by dimanech** [ismay/stylelint-no-unsupported-browser-features#12]
Hi, 
Thank you for great plugin!
It would be nice if plugin use `browserslist` field from package.json or check all browser list source.

**Comment by ismay** [comment]
I agree. This library uses doiuse, which currently doesn't use browserslist in the documented way but uses its own parsing logic. There's an open issue on the browserslist repo about exactly that (you're not the first to report this): https://github.com/anandthakker/doiuse/issues/67. So please look there for updates on parsing the browserslist. As soon as it's fixed there I'll update it here as well 👍
