### ISSUE TITLE
Upgrade doiuse

### ISSUE THREAD

**Issue by tranvansang** [ismay/stylelint-no-unsupported-browser-features#149]
Related issue: https://github.com/postcss/postcss/issues/1561

Hello,

Thank you very much for the great package.

Currently, I am facing this error when running stylelint with `stylelint-no-unsupported-browser-features` enabled.

```
(node:1333057) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /home/transang/artflag/node_modules/doiuse/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

The culprit is only because of the old `doiuse` version included in `stylelint-no-unsupported-browser-features`. This old `doiuse` import old `postcss` version which causes the deprecation warning.

Could you please upgrade the `doiuse` version so I can continue using this `stylelint-no-unsupported-browser-features` plugin?

**Comment by ismay** [comment]
Hi @tranvansang,

- The version we're specifying in package.json for this lib is ^4.3.1: https://github.com/ismay/stylelint-no-unsupported-browser-features/blob/master/package.json#L20
- The latest version of doiuse is 4.3.1: https://github.com/anandthakker/doiuse

**Comment by ismay** [comment]
I've closed the issue since it doesn't seem like there's an issue with the version of doiuse we've specified in package.json. However, please let me know if there has been an oversight or if there's anything else that seems off! Hope that helps 😊!

**Comment by tranvansang** [comment]
hmm,

It looks like the latest `doiuse` version is `4.4.1`.

https://www.npmjs.com/package/doiuse/v/4.4.1

**Comment by ismay** [comment]
> hmm,
> 
> It looks like the latest `doiuse` version is `4.4.1`.
> 
> https://www.npmjs.com/package/doiuse/v/4.4.1

Ah I guess their GH releases page hasn't been updated alongside their npm publishes, that lists 4.3.1: https://github.com/anandthakker/doiuse/releases. Still, the range we specify is `"^4.3.1"`, so doiuse 4.4.1 will still be installed if your other dependencies allow it. See here https://semver.npmjs.com:

<img width="866" alt="Screenshot 2021-05-21 at 21 10 38" src="https://user-images.githubusercontent.com/7355199/119187113-33ee5a80-ba79-11eb-82fb-1bdff2091cc4.png">

**Comment by tranvansang** [comment]
I've successfully bumped doiuse to the latest version. Now, the deprecation warning is gone.

```bash
yarn remove stylelint-no-unsupported-browser-features
yarn add doiuse
yarn add -D stylelint-no-unsupported-browser-features
yarn remove doiuse
git add yarn.lock
```

Thanks very much for your time, and have a nice weekend.

**Comment by ismay** [comment]
Thanks for the help @tranvansang! Since the latest version of doiuse fixed the issue, I've bumped the version for this plugin to 4.4.1. that should resolve it for everyone. I've also done some other housekeeping, all that has been releases as v5. Let me know if anything comes up!
