### ISSUE TITLE
Not getting warnings for logical border-radius properties

### ISSUE THREAD

**Issue by t0byman** [ismay/stylelint-no-unsupported-browser-features#155]
These 4 logical properties won't trigger a no supported warning for Safari, how come?

- border-start-start-radius
- border-start-end-radius
- border-end-start-radius
- border-end-end-radius

Caniuse says they aren't supported by Safari so shouldn't I get the warnings? I'm using @wordpress/browserslist-config so my browserslist is:

`"> 1%",
"last 1 Android versions",
"last 1 ChromeAndroid versions",
"last 2 Chrome versions",
"last 2 Firefox versions",
"last 2 Safari versions",
"last 2 iOS versions",
"last 2 Edge versions",
"last 2 Opera versions",`

**Comment by ismay** [comment]
See my comment here: https://github.com/ismay/stylelint-no-unsupported-browser-features/issues/146#issuecomment-811118513. Please open an issue in the doiuse repo. Thanks!
