### ISSUE TITLE
Question: Does this project check to see if the vendor prefix exists to add support for an unsupported browser?

### ISSUE THREAD

**Issue by JeffersonBledsoe** [ismay/stylelint-no-unsupported-browser-features#156]
GitHub Discussions isn't enabled for this repo, so sorry for the question as an issue.

I just wondered if this stylelint plugin will check to see if a vendor prefix for a property exists before displaying a warning? For example, let's say we use `display: grid` and want to support IE11. On it's own, `display: grid` won't work, but if we include `display: -ms-grid`, we get grid support.

**Comment by ismay** [comment]
> GitHub Discussions isn't enabled for this repo, so sorry for the question as an issue.

Good idea, I've enabled discussions 👍

> I just wondered if this stylelint plugin will check to see if a vendor prefix for a property exists before displaying a warning? For example, let's say we use `display: grid` and want to support IE11. On it's own, `display: grid` won't work, but if we include `display: -ms-grid`, we get grid support.

This plugin uses doiuse for checking support. See here: https://github.com/ismay/stylelint-no-unsupported-browser-features/issues/137#issuecomment-766665032
