### ISSUE TITLE
Maintaince for doiuse

### ISSUE THREAD

**Issue by ai** [ismay/stylelint-no-unsupported-browser-features#18]
doiuse right now have no active maintainer. Maybe you want to maintain it as author of `stylelint-no-unsupported-browser-features` (great plugin, thanks).

@ismay I didn’t find your email to add your to our discussion.

**Comment by ismay** [comment]
@ai Oh yeah, I'd be happy to. Good work on the doiuse 3.0 release btw! My email is ismay@ismaywolff.nl. Would be nice to get some work done on doiuse!

**Comment by ismay** [comment]
@anandthakker, @ai, Any news on this? If I can help just let me know.

**Comment by ai** [comment]
@anandthakker was ready to take access :) but seems like forgot about it.

**Comment by ismay** [comment]
Ah ok, well I'm available if help is needed 👍  I'll close this, but feel free to ping me @anandthakker.

**Comment by anandthakker** [comment]
@ismay added you as a collaborator -- welcome and thanks!
