### ISSUE TITLE
ignorePartialSupport usage

### ISSUE THREAD

**Issue by ashil88** [ismay/stylelint-no-unsupported-browser-features#230]
Hi

I recently updated my stylelint packages to the latest versions (including this one to v5.0.2). When I run the lint command now, it's flagging 'only partially supported' warnings on multiple css files (no idea why these weren't being flagged before as they are valid warnings). I was hoping that the `ignorePartialSupport` setting would supress these warnings until we address them individually, but the issues are still being flagged when I run the command... Just wondering if there's an issue, or am I just using it incorrectly/not understanding what this option actually does?

This is our implementation in stylelint.rc:
`"rules": {
    "plugin/no-unsupported-browser-features": [true, {
        "ignore": ["rem", "calc"],
        "ignorePartialSupport": true,
        "severity": "warning"
    }],
    ...
}`

Any help would be appreciated.

Thanks
Ashil

**Comment by ismay** [comment]
Hi @ashil88,

When enabled this is what ignorePartialSupport does:

> Rules that only trigger partial violations will be ignored.
> Rules that trigger both partial and full violations will only report on the full support violations.
> Rules that trigger only full support violations will not be affected.

The current tests for ignorePartialSupport all succeed: https://github.com/ismay/stylelint-no-unsupported-browser-features/blob/master/lib/index.test.js#L171, so it seems that everything's working as expected.

If you think that you've found an edge case please submit a PR with a failing test and we can take a look at it. Thanks!

**Comment by ismay** [comment]
Ok I see. Assuming that your (@timogasda) issue is identical to that of @ashil88 then we should start by reproducing this with a failing test. Because weirdly, @timogasda's  example matches one of the existing unit tests almost exactly: https://github.com/ismay/stylelint-no-unsupported-browser-features/blob/master/lib/index.test.js#L174. And there it's correctly ignoring the partial support.

Would you mind adding a failing test that reproduces the error from your last example @timogasda?

**Comment by timogasda** [comment]
Happy to help! I opened a PR with the test case and a fix for it :) 

https://github.com/ismay/stylelint-no-unsupported-browser-features/pull/231

**Comment by ismay** [comment]
> Happy to help! I opened a PR with the test case and a fix for it :)
> 
> #231

Thanks! I'll try and take a look at it this week
