### ISSUE TITLE
This plugin should ignore [development] environment

### ISSUE THREAD

**Issue by jitendravyas** [ismay/stylelint-no-unsupported-browser-features#26]
https://github.com/ai/browserslist#environments

**Comment by ismay** [comment]
@jitendravyas Could you clarify? Way I see it the current behaviour is fine. You can just set environment variables to specify the environment you want to use and it'll fallback to defaults if nothing can be found.

**Comment by jitendravyas** [comment]
ok.

**Comment by ismay** [comment]
I'll close this, but feel free to clarify if you believe otherwise though. If there are any arguments to change the default behavior I'd to open to discussing them. It's just that I currently am not aware of any reasons to do so.
