### ISSUE TITLE
Can't get browserlist in package.json or browserlist file to be recognised

### ISSUE THREAD

**Issue by benlane** [ismay/stylelint-no-unsupported-browser-features#27]
The only way I seem to be able to get the browserlist to be recognised is by setting it in the configuration for the plugin directly using the browsers option rather than having it in the package.json or a browserlist file in the root of the project.

I am using atom and the plugin and stylelint versions should be the latest as I only installed them on the project today.

Is there an example of this working with the package.json or browserlist file configuration.

my stylelint config is as follows

`
{
    "plugins": [
        "stylelint-no-unsupported-browser-features"
    ],
    "rules": {
        "plugin/no-unsupported-browser-features": [true, { "severity": "warning", "ignore": ['rem']}]
    }
}`

**Comment by ismay** [comment]
That seems to be a bug in https://github.com/AtomLinter/linter-stylelint. The version of browserslist shipped with this plugin ([2.1.2](https://github.com/anandthakker/doiuse/blob/master/package.json#L30)) should pick up any config just fine (see browserslist documentation)

For an example config see [here](https://github.com/ismay/ismaywolff.nl/blob/develop/.browserslistrc). For me it works fine. But I've encountered the same bug in atom with linter-stylelint. Restarting atom fixed it for me, but it's still not convenient. I suggest opening an issue with linter-stylelint, but please do report back if you find evidence of anything going wrong in this library.

**Comment by Arcanemagus** [comment]
Turns out this was a bug in `doiuse`, fixed in https://github.com/anandthakker/doiuse/pull/72.

**Comment by ismay** [comment]
Fixed in doiuse 3.0.1
