### ISSUE TITLE
Unexpected browser feature "multicolumn" is only partially supported by Edge 111,112, Firefox 111,112, Chrome 111,112 plugin/no-unsupported-browser-features

### ISSUE THREAD

**Issue by MrVladevoit** [ismay/stylelint-no-unsupported-browser-features#272]
Hello
Please tell me why the plugin shows this error "Unexpected browser feature "multicolumn" is only partially supported by Edge 111,112, Firefox 111,112, Chrome 111,112 plugin/no-unsupported-browser-features", when this property has been supported in all [browsers](https://caniuse.com/mdn-css_properties_grid-template-columns) for a long time (in chrome from version 57).
I want to understand why the **grid-template-columns** property shows the message.
Thank you

**Comment by MrVladevoit** [comment]
@ismay , but I use LESS preprocessor and want to know, which approach suits me best. Because I can't use doiuse.
Thanks

**Comment by ismay** [comment]
> @ismay , but I use LESS preprocessor and want to know, which approach suits me best. Because I can't use doiuse.
Thanks

Then I'm afraid this tool is not compatible. As it says in the readme:

> Doiuse and this plugin are only compatible with standard css syntax, so syntaxes like scss, less and others aren't supported.

All this plugin does is provide an interface between doiuse and stylelint. The actual detection is done by doiuse, so if doiuse doesn't support it we probably don't either (unless stylelint is able to transform between the less you're writing and the css doiuse expects). Similar with detection, this plugin only reports what doiuse tells it.

At any rate, this is not a support forum. You should only use issues for reporting verified bugs or requesting features. If you have questions about usage please use the discussions tab.

**Comment by MrVladevoit** [comment]
Got it, thank you !
