### ISSUE TITLE
rgba(0,0,0,0%) still flagged by stylelint

### ISSUE THREAD

**Issue by mgatto** [ismay/stylelint-no-unsupported-browser-features#290]
Hi,

Stylelint warns that `rgba(0,0,0,0%)` should have a modern syntax by using spaces as separators rather than commas. 

My browserslist config signals that project must support iOS 11 and above. However, https://caniuse.com/mdn-css_types_color_rgba_space_separated_parameters shows that iOS Safari 11 doesn't support spaces and must have commas instead. 

I would like this plugin to prevent this warning by stylelint. I currently use version 5.0.4 due to being obliged to use nodejs 12 for the time being. Doiuse is at version 4.4.1.

I have checked `doiuse` on the command line and it correctly IMHO does not flag `rgba(0,0,0,0%)` as unsupported (it's not in the output). 

Thanks.

**Comment by ismay** [comment]
Hi @mgatto,

If doiuse doesn't flag the line then this plugin does not have anything to do with the warning. It merely passes on what doiuse finds.

What you're seeing is the output of this rule: https://stylelint.io/user-guide/rules/color-function-notation/. I don't think it's in the scope of this plugin to control external rules. If you don't want to see that specific linting error you should disable it in your stylelint config.
