### ISSUE TITLE
Move stylelint as a peerDependency

### ISSUE THREAD

**Issue by mike3run** [ismay/stylelint-no-unsupported-browser-features#50]
Stylelint is already at v8 and we're still adding v5 here so maybe something along the line of peer dependencies would work fine:

```js
"peerDependencies": {
  "stylelint": ">=5.0.0" 
}
```

**Comment by mike3run** [comment]
<img width="1623" alt="screen shot 2017-12-16 at 2 43 43 pm" src="https://user-images.githubusercontent.com/7088511/34074203-9bc9da16-e26f-11e7-9554-15201d60d4f0.png">

**Comment by ismay** [comment]
Yeah that seems like a good idea. Thanks for the suggestion!

**Comment by mike3run** [comment]
@ismay here's a PR for you to take a look at 😄 
https://github.com/ismay/stylelint-no-unsupported-browser-features/pull/51
