### ISSUE TITLE
2 instead of true in the README and tests

### ISSUE THREAD

**Issue by jeddy3** [ismay/stylelint-no-unsupported-browser-features#6]
Plugin code looks great!

I had a query about what the `2`s in the README and tests configs. Should those `2`s be `true`s instead, e.g?:

```json
{
  "plugins": [
    "stylelint-no-unsupported-browser-features"
  ],
  "rules": {
    "plugin/no-unsupported-browser-features": [true, {
      "browsers": ["> 1%", "Last 2 versions"],
      "ignore": ["rem"]
    }]
  }
}
```

And

```js
config: [true, { browsers: ['IE 8'] }],
```

**Comment by ismay** [comment]
@jeddy3 You're right, they should. I think that got in there because I based the config on examples elsewhere. Thanks!
