### ISSUE TITLE
doiuse update

### ISSUE THREAD

**Issue by katasup** [ismay/stylelint-no-unsupported-browser-features#68]
Hi! The issue with `font unicode range` has been [fixed](https://github.com/anandthakker/doiuse/pull/80) in `doiuse@4.1`, so it's time to update dependency?

![2018-03-26 15 09 54](https://user-images.githubusercontent.com/3366664/37905656-30565984-3108-11e8-9990-2c69c5671c1a.png)

**Comment by ismay** [comment]
https://github.com/ismay/stylelint-no-unsupported-browser-features/pull/67
