### ISSUE TITLE
Plugin doesnt recognize nither browserslist nor .browserslistrc file

### ISSUE THREAD

**Issue by budarin** [ismay/stylelint-no-unsupported-browser-features#70]
Add plugin into my stylintrc file as described

```
"plugins": [
        "stylelint-order",
        "stylelint-no-unsupported-browser-features"
    ],
    "rules": {
        "plugin/no-unsupported-browser-features": [true, {
            "severity": "warning"
        }],
```
also have created browserslist and .browserslistrc files and added list into package.json 
```
Chrome >= 63
Firefox >= 58
Safari >= 11.11
iOS >= 10.3
Edge >= 41
```
but plugin doesnt recognizes browsers list
only by adding browsers list into .stylelintrc force the plugin to work

**Comment by ismay** [comment]
This plugin relies on doiuse to retrieve the browserslist browsers. So for bugs regarding that I recommend you to open an issue with the doiuse repository.

Also, when opening an issue like this it helps to include all the information necessary to reproduce the problem from start to finish. For example, an example repository really helps. Right now I don't know whether you're running stylelint in atom, from the cli, or something else.
