### ISSUE TITLE
plugin fails to load - "plugin/no-unsupported-browser-features" rule not found

### ISSUE THREAD

**Issue by Goldziher** [ismay/stylelint-no-unsupported-browser-features#90]
*** reproduction repository will come in the future, apologies.

I cannot use this plugin - I've tried multiple times, but whenever I try to run stylelint with this plugin this is the result:

```Error: Undefined rule plugin/no-unsupported-browser-features
    at module.exports (workspacee/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at workspacee/node_modules/stylelint/lib/augmentConfig.js:325:13
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (workspacee/node_modules/stylelint/lib/augmentConfig.js:318:29)
    at workspacee/node_modules/stylelint/lib/augmentConfig.js:94:14```

these are my configs:

```module.exports = {
	"extends": [
		"stylelint-config-recommended-scss",
		"stylelint-config-recess-order",
		"stylelint-prettier/recommended",
		"stylelint-no-unsupported-browser-features"
	],
	"rules": {
		"no-empty-source": null,
		"plugin/no-unsupported-browser-features": [true, {
			"severity": "warning"
		}]
	},
}
```

I have tried different variations, but the error is always the same.

package.json is updated to the latest version of stylelint and all related packages using node-check-update.

I also have a browserlist entry in the package.json:

```"browserlist": [
		"defaults",
		"IE 11"
	]```

**Comment by ismay** [comment]
> *** reproduction repository will come in the future, apologies.

If it's a legitimate bug we should definitely take a look at it. But until you have more details for me I can't take a look at this. Your output and code samples are cut off as well, so I can't say what went wrong here. I'll close it for now, if you have more details we can open it again.
